author:
  name             : "Tan Zhe Yue"
  avatar           : "/images/profile.jpg"
  bio              : "Form 1 student at Chung Ling Private High School, passionate about robotics, technology, and innovation. Winner of national and international competitions including DUTA, FLL, and ISIC."
  location         : "Penang, Malaysia"
  employer         : "Chung Ling Private High School"
  email            : "zy.tan988@gmail.com"
  github           : "zhe-yue922"
